### ISSUE TITLE
Unable to use Ginger Agent with jre 1.5

### ISSUE THREAD

**Issue by Salsabeelyf** [Ginger-Automation/Ginger#1670]
**Describe the bug**
I have a jnlp application that can only be run using jre 1.5. I need to use GingerAgent with this application. 
When I try to attach GingerAgent to it, an exception is thrown that says:
com.sun.tools.attach.AttachNotSupportedException: The VM does not support the attach mechanism
        at sun.tools.attach.HotSpotAttachProvider.testAttachable(HotSpotAttachProvider.java:152)
        at sun.tools.attach.WindowsAttachProvider.attachVirtualMachine(WindowsAttachProvider.java:50)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:195)
        at com.amdocs.ginger.GingerAgent.Attach(GingerAgent.java:150)
        at com.amdocs.ginger.GingerAgent.main(GingerAgent.java:89)

**To Reproduce**
1. Start jnlp file with jre 1.5
2. Start GingerAgent with jdk 1.8 for example, give it PID of the application you already started in step 1.
3. see error.

**Expected behavior**
Ginger agent should be attached to the application

**Desktop
 - OS: Windows 10

**Comment by Salsabeelyf** [comment]
@ravikirankethe

**Comment by JinendraGhodke** [comment]
1. You need to use the same JDK version to launch and Attach the Java agent. (Launching with JRE and attaching with JDK will not work)
2. Ginger supports JDK v1.6_29 or above

**Comment by JinendraGhodke** [comment]
Please confirm if this issue is resolved

**Comment by JinendraGhodke** [comment]
Marking this issue as closed based on the above answer. If the issue still persist please reopen
