### ISSUE TITLE
Ginger v37.0.0.0 - Java Agent getting stuck on "Agent is starting..." 

### ISSUE THREAD

**Issue by EnriqueGalindoCardenas** [Ginger-Automation/Ginger#1886]
Creating a new agent to manipulate Java application  (CRM) and trying to Test Agent its getting stuck on status "Agent is starting..."

IP and port are correct configured according with Java application configuration

1. Go to 'CONFIGURATIONS'
2. Click on 'Add Item'
3. Click on "Next ->" button
4. Set Name
5. Select Plataform as "Java"
6. Select Diver as "Java Driver"
7. Select Type as "JavaDriver"
8. Click on "Next ->" button
9. Set Java AgentHost - IP value obtained from java CRM application
10. Set Java AgentPort - Port value obtained from java CRM application
11. Click on "Finish" button
12. Select your Agent just created and click on "Test Agent" button

Here button is disabled trying to test agent but there is no change anymore, then if I click on "BUSINESS FLOWS" menu I can see close to the "power" button a status "Agent is starting..."

LOGS (INFO log is present all time when status is "Agent is starting..." then ERROR log was created when I close Java application after 10 minutes) 

2021-05-05 12:03:19,548 | INFO  | NTNET\enriquga | [1] | Amdocs.Ginger.CoreNET.log4netLib.GingerLog |:
Showing Status Message: Starting the agent 'E2EC' for 'MyJavaApp'

2021-05-05 12:06:20,644 | ERROR | NTNET\enriquga | [1] | Amdocs.Ginger.CoreNET.log4netLib.GingerLog |:
System.Exception: String Parsing Error/wrong value type b=2 Name of the payload isERROR Buffer Index is: 14
   at GingerCore.Drivers.CommunicationProtocol.PayLoad.GetValueString()
   at GingerCore.Drivers.JavaDriverLib.JavaDriver.StartDriver() in D:\BuildConfigs\tfsagent\_work\4\s\Ginger\GingerCore\Drivers\JavaDriverLib\JavaDriver.cs:line 167
   at Ginger.Repository.RepositoryItemFactory.StartAgentDriver(IAgent IAgent) in D:\BuildConfigs\tfsagent\_work\4\s\Ginger\Ginger\AutomatePageLib\AddActionMenu\SharedRepositoryLib\RepositoryItemFactory.cs:line 252
   at GingerCore.Agent.StartDriver()
   at Ginger.Agents.ApplicationAgentsMapPage.xStartCloseAgentBtn_Click(Object sender, RoutedEventArgs e) in D:\BuildConfigs\tfsagent\_work\4\s\Ginger\Ginger\Agents\ApplicationAgentsMapPage.xaml.cs:line 107
   at Amdocs.Ginger.UserControls.ucButton.xButton_Click(Object sender, RoutedEventArgs e) in D:\BuildConfigs\tfsagent\_work\4\s\Ginger\Ginger\UserControlsLib\GingerButtons\ucButton.xaml.cs:line 166
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
System.Exception: String Parsing Error/wrong value type b=2 Name of the payload isERROR Buffer Index is: 14
   at GingerCore.Drivers.CommunicationProtocol.PayLoad.GetValueString()
   at GingerCore.Drivers.JavaDriverLib.JavaDriver.StartDriver() in D:\BuildConfigs\tfsagent\_work\4\s\Ginger\GingerCore\Drivers\JavaDriverLib\JavaDriver.cs:line 167
   at Ginger.Repository.RepositoryItemFactory.StartAgentDriver(IAgent IAgent) in D:\BuildConfigs\tfsagent\_work\4\s\Ginger\Ginger\AutomatePageLib\AddActionMenu\SharedRepositoryLib\RepositoryItemFactory.cs:line 252
   at GingerCore.Agent.StartDriver()
   at Ginger.Agents.ApplicationAgentsMapPage.xStartCloseAgentBtn_Click(Object sender, RoutedEventArgs e) in D:\BuildConfigs\tfsagent\_work\4\s\Ginger\Ginger\Agents\ApplicationAgentsMapPage.xaml.cs:line 107
   at Amdocs.Ginger.UserControls.ucButton.xButton_Click(Object sender, RoutedEventArgs e) in D:\BuildConfigs\tfsagent\_work\4\s\Ginger\Ginger\UserControlsLib\GingerButtons\ucButton.xaml.cs:line 166
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

--------------------------------------------------------------------
JAVA VERSION

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) Client VM (build 25.201-b09, mixed mode, sharing)

OS Windows 10 64 bit
Core i5
8 GB RAM

**Comment by JinendraGhodke** [comment]
In the agent configuration, the IP and port is not the CRM application host and port. 
This is the host and port using which Ginger will communicate with CRM. 
You need to add the Launch Java WS action, which will attach the ginger agent to the CRM application. 
And then this action should have the same port as configured on the agent. 

For more details click F1 from anywhere in Ginger.  Built-in help library will open. Search for How to use java driver and follow the steps

**Comment by JinendraGhodke** [comment]
Please confirm if this issue is resolved

**Comment by JinendraGhodke** [comment]
Marking this issue as closed based on the above answer. If the issue still persist please reopen
