### ISSUE TITLE
FarEye | Ginger 4.1 Linux Runner | Issue with Directory creation using Jenkins & Ginger

### ISSUE THREAD

**Issue by vaibhav-rastogi** [Ginger-Automation/Ginger#2223]
**Describe the bug**
While Executing Ginger Linux Runner through Ginger Jenkins Plugin its not creating correct directory format

**To Reproduce**
1. Setup Jenkins Node for Unix
2. Configure Package for execution
3. Node Directory Path - /home/username/Downloads/Remote
4. Start the Execution using Jenkins

**Expected behavior**
Ginger Should Create Files under /home/vaibhav/Downloads/Remote/workspace/GingerPOC/tempConfig.xml & home/vaibhav/Downloads/Remote/workspace/GingerPOC/GingerPOC.git/SmokePOC

**Actual behavior**
Ginger Should Create Files under /home/vaibhav/Downloads/Remote/workspace/GingerPOC\tempConfig.xml & home/vaibhav/Downloads/Remote/workspace/GingerPOC\GingerPOC.git\SmokePOC

Ubuntu considering GingerPOC\tempConfig.xml as file name rather GingerPOC folder and tempConfig.xml as file

**Jenkins Logs**
Started by user Vaibhav Rastogi
Running as SYSTEM
Building remotely on Node1 in workspace /home/vaibhav/Downloads/Remote/workspace/GingerPOC
Executingginger ConfigFile="/home/vaibhav/Downloads/Remote/workspace/GingerPOC\tempConfig.xml"
$ ginger ConfigFile=/home/vaibhav/Downloads/Remote/workspace/GingerPOC\tempConfig.xml
[INFO | 16:38:21:116_06-Jan] 
*******************************************************************************************************************
Ginger by Amdocs
Version: 4.1
Executer Path: /opt/ginger/GingerRuntime.dll
Log File Path: /home/vaibhav/.config/amdocs/Ginger/WorkingFolder/Logs/Ginger_Log.txt
*******************************************************************************************************************

[INFO | 16:38:21:146_06-Jan] Processing command line arguments...

[INFO | 16:38:21:400_06-Jan] Loading User Profile

[WARN | 16:38:21:410_06-Jan] Failed to get/create the Common users Ginger workspace folder path
Exception Details:
Error:Access to the path '/usr/share/amdocs/Ginger' is denied.
Source:System.IO.FileSystem
Stack Trace:    at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Amdocs.Ginger.Common.GeneralLib.General.get_CommonApplicationDataFolderPath() in D:\BuildConfigs\tfsagent\_work\4\s\Ginger\GingerCoreCommon\GeneralLib\General.cs:line 51

[INFO | 16:38:21:411_06-Jan] Creating new User Profile

[INFO | 16:38:21:412_06-Jan] Configuring User Type

[WARN | 16:38:21:416_06-Jan] You are using old style command line arguments which are obsolete!

[WARN | 16:38:21:416_06-Jan] Instead of using: System.String[]

[WARN | 16:38:21:416_06-Jan] You can use: System.String[]

[INFO | 16:38:21:484_06-Jan] Running with config file = '/home/vaibhav/Downloads/Remote/workspace/GingerPOC\tempConfig.xml'

[INFO | 16:38:21:497_06-Jan] Loading Solution...

[INFO | 16:38:21:498_06-Jan] Downloading/updating Solution from source control

[INFO | 16:39:04:481_06-Jan] Loading the Solution '/home/vaibhav/Downloads/Remote/workspace/GingerPOC\GingerPOC.git\SmokePOC'

[INFO | 16:39:04:482_06-Jan] Loading Solution- Cleaning previous Solution items

[INFO | 16:39:04:482_06-Jan] Solution Closed

[INFO | 16:39:04:483_06-Jan] Loading Solution- Loading Solution File: '/home/vaibhav/Downloads/Remote/workspace/GingerPOC\GingerPOC.git\SmokePOC/Ginger.Solution.xml'

[INFO | 16:39:04:483_06-Jan] Loading Solution- Checking if Ginger Solution items upgrade is needed

[INFO | 16:39:04:525_06-Jan] Loading Solution- Loading Solution file xml into object

[WARN | 16:39:04:546_06-Jan] Encryption Key was not found in OS passwords store

[ERROR | 16:39:04:553_06-Jan] Loading Solution- Error: Encryption key validation failed

[WARN | 16:39:04:553_06-Jan] Issue occured while doing CLI Load and Prepare so aborting execution

[ERROR | 16:39:04:553_06-Jan] Error(s) occurred process exit code (1)

[INFO | 16:39:04:554_06-Jan] Processing command line arguments completed

ERROR: 1
Finished: FAILURE

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by vaibhav-rastogi** [comment]
This issue still exist with Latest Ginger Jenkins Plugin 3.1

**Comment by Maheshkale447** [comment]
Hi Vaibhav, Can you please share latest jenkins logs from Ginger Jenkins Plugin 3.1

**Comment by vaibhav-rastogi** [comment]
I have uninstalled Plugin as it was not working. Last Jenkins Logs and Ginger CLI logs are mentioned in the Defect Description

**Comment by vaibhav-rastogi** [comment]
Started by user Vaibhav Rastogi
Running as SYSTEM
Building remotely on GingerUnix in workspace /home/vaibhav/Downloads/Remote/workspace/GingerUnixPOC
$ ginger run --type GIT --url https://github.com/vaibhav-rastogi/GingerPOC.git --user vaibhav-rastogi --pass YpITj7c9Y4bdLXPI0xv1R4RoX4oZ6u8MnoXMi94GizSpbXomRkqgjn0V9T8Nw9c8 --encrypted --solution /home/vaibhav/Downloads/Remote/workspace/GingerUnixPOC\GingerPOC.git\GingerUnixPOC --env QA-Test --runset Test --encryptionKey "w9y$B&E)" --do-not-analyze False --showui False
[INFO | 16:38:48:813_27-Jan] 
*******************************************************************************************************************
Ginger by Amdocs
Version: 4.2.1(Beta, Build Date: 05-Jan-2022)
Executer Path: /opt/ginger/GingerRuntime.dll
Log File Path: /home/vaibhav/.config/amdocs/Ginger/WorkingFolder/Logs/Ginger_Log.txt
*******************************************************************************************************************



[INFO | 16:38:48:821_27-Jan] Processing command line arguments...

[INFO | 16:38:48:963_27-Jan] Loading User Profile

[WARN | 16:38:48:969_27-Jan] Failed to get/create the Common users Ginger workspace folder path
Exception Details:
Error:Access to the path '/usr/share/amdocs/Ginger' is denied.
Source:System.IO.FileSystem
Stack Trace:    at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Amdocs.Ginger.Common.GeneralLib.General.get_CommonApplicationDataFolderPath() in D:\BuildConfigs\tfsagent\_work\2\s\Ginger\GingerCoreCommon\GeneralLib\General.cs:line 51

[INFO | 16:38:48:971_27-Jan] Creating new User Profile

[INFO | 16:38:48:972_27-Jan] Configuring User Type

[INFO | 16:38:49:038_27-Jan] ######## Starting Automatic Run Set Execution Process ########

[INFO | 16:38:49:039_27-Jan] Parsing Run Set execution arguments...

[INFO | 16:38:49:039_27-Jan] Solution: '/home/vaibhav/Downloads/Remote/workspace/GingerUnixPOC\GingerPOC.git\GingerUnixPOC'

[INFO | 16:38:49:039_27-Jan] Runset: 'Test'

[INFO | 16:38:49:039_27-Jan] Environment: 'QA-Test'

[INFO | 16:38:49:039_27-Jan] Loading Configurations...

[INFO | 16:38:49:048_27-Jan] Loading Solution...

[INFO | 16:38:49:049_27-Jan] Downloading/updating Solution from source control

Cloning into '.'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/vaibhav-rastogi/GingerPOC.git/'

[INFO | 16:38:50:635_27-Jan] Showing User Message: 'Application error occurred.
Error Details: ''.'

Error Occurred
Application error occurred.
Error Details: ''.
[INFO | 16:38:50:635_27-Jan] User Message Option Selection: 'None'

[ERROR | 16:38:50:636_27-Jan] Failed to Download/update Solution from source control

[INFO | 16:38:50:638_27-Jan] Loading the Solution '/home/vaibhav/Downloads/Remote/workspace/GingerUnixPOC\GingerPOC.git\GingerUnixPOC'

[INFO | 16:38:50:638_27-Jan] Loading Solution- Cleaning previous Solution items

[INFO | 16:38:50:639_27-Jan] Solution Closed

[INFO | 16:38:50:639_27-Jan] Loading Solution- Loading Solution File: '/home/vaibhav/Downloads/Remote/workspace/GingerUnixPOC\GingerPOC.git\GingerUnixPOC/Ginger.Solution.xml'

[ERROR | 16:38:50:640_27-Jan] Loading Solution- Error: Solution File Not Found

[WARN | 16:38:50:640_27-Jan] Issue occured while doing CLI Load and Prepare so aborting execution

[ERROR | 16:38:50:640_27-Jan] Error(s) occurred process exit code (1)

[INFO | 16:38:50:640_27-Jan] Processing command line arguments completed

ERROR: 1
Finished: FAILURE
