### ISSUE TITLE
Agent: SeleniumEdge error: Exception in start driver

### ISSUE THREAD

**Issue by charlenecordero** [Ginger-Automation/Ginger#2944]
2023-04-08 16:23:15,886 | ERROR | NTNET\charleco | [30] | Amdocs.Ginger.CoreNET.log4netLib.GingerLog |:
Exception in start driver
System.InvalidOperationException: session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 109
Current browser version is 112.0.1722.34 with binary path C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe (SessionNotCreated)
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeDriverService service, EdgeOptions options, TimeSpan commandTimeout)
   at GingerCore.Drivers.SeleniumDriver.StartDriver() in D:\BuildConfigs\tfsagent\_work\4\s\Ginger\GingerCoreNET\Drivers\CoreDrivers\Web\Selenium\SeleniumDriver.cs:line 350

**Comment by digvijayAMDX** [comment]
Hi @charlenecordero,
The error says, the MS Edge Webdriver (MSEdgedriver.exe) version that was included by default in the Ginger version, is v109  but your current MS Edge browser version is higher than that i.e. 112.0.1722.34 

So you must download the MS Edge Webdriver version which is meant for you current MS edge browser version. Once downloaded, you can move the MSEdgedriver.exe from the extracted package to the directory where Ginger.exe is running and this issues should be resolved for you. 

Generally for the default Ginger installation, the path should be "C:\Program Files (x86)\Amdocs\Ginger by amdocs"
