### ISSUE TITLE
Sequence contains no matching element when generating report

### ISSUE THREAD

**Issue by x-vii03** [Ginger-Automation/Ginger#3703]
**Describe the bug**
After a successful test execution run and generate report has been trigger, this error is returned:

RunNewHtmlReport,error :System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Amdocs.Ginger.CoreNET.Logger.WebReportGenerator.RunNewHtmlReport(String reportResultsFolderPath, String runSetGuid, WebReportFilter openObject, Boolean shouldDisplayReport) in D:\a\Ginger\Ginger\Ginger\GingerCoreNET\Logger\WebReportGenerator.cs:line 99

**To Reproduce**
1. Go to Business Flow Automate
2. Click on Run Flow
3. Click Generate report

**Expected behavior**
Report is generated and automatically opened in new browser

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome Version 123.0.6312.106
 - Version: Windows 10 64 Bit

**Additional context**
RunNewHtmlReport,error :System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Amdocs.Ginger.CoreNET.Logger.WebReportGenerator.RunNewHtmlReport(String reportResultsFolderPath, String runSetGuid, WebReportFilter openObject, Boolean shouldDisplayReport) in D:\a\Ginger\Ginger\Ginger\GingerCoreNET\Logger\WebReportGenerator.cs:line 99

**Comment by x-vii03** [comment]
Issue has been resolved.
